// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPs5IVP2dkbpScmcRetWjOkHUFZ9Rzpoc',
    appId: '1:453378297645:web:879dc910a0147edd2c8da4',
    messagingSenderId: '453378297645',
    projectId: 'proyectocinema-43a30',
    authDomain: 'proyectocinema-43a30.firebaseapp.com',
    storageBucket: 'proyectocinema-43a30.appspot.com',
    measurementId: 'G-8M4Z5Z3RJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhVNe00oEwNiJQ7huDpsbKzHhKcwVB3sw',
    appId: '1:453378297645:android:c7b4a8c9b3ed68472c8da4',
    messagingSenderId: '453378297645',
    projectId: 'proyectocinema-43a30',
    storageBucket: 'proyectocinema-43a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAJIMYUqCC24gNUWc0RfpQSDnjeAYn45Q',
    appId: '1:453378297645:ios:716f2fcbe30e9ae22c8da4',
    messagingSenderId: '453378297645',
    projectId: 'proyectocinema-43a30',
    storageBucket: 'proyectocinema-43a30.appspot.com',
    iosBundleId: 'com.example.proyectoCinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAJIMYUqCC24gNUWc0RfpQSDnjeAYn45Q',
    appId: '1:453378297645:ios:716f2fcbe30e9ae22c8da4',
    messagingSenderId: '453378297645',
    projectId: 'proyectocinema-43a30',
    storageBucket: 'proyectocinema-43a30.appspot.com',
    iosBundleId: 'com.example.proyectoCinema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPs5IVP2dkbpScmcRetWjOkHUFZ9Rzpoc',
    appId: '1:453378297645:web:ecf4aab2943d35152c8da4',
    messagingSenderId: '453378297645',
    projectId: 'proyectocinema-43a30',
    authDomain: 'proyectocinema-43a30.firebaseapp.com',
    storageBucket: 'proyectocinema-43a30.appspot.com',
    measurementId: 'G-00H73VR6TE',
  );

}